
@startuml
title Альтернативная диаграмма контейнеров системы АгроТех Х PigSystem

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

System_Ext(cntIdP, "Identity Provider", "Управляет аккаунтами пользователей и их правами доступа\n\nПроводит через аутентификацию")
System_Ext(cntAPIGateway, "API Gateway", "Kong Gateway", "Валидирует токены доступа\nМаршрутизирует запросы")

System(backCenter, "Центральный сервер"," ")
Container_Boundary(backCenter, "") {
    Container(bffWeb, "API для Web-приложения", "Backend for frontend")
    Container(bffMobile, "API для мобильного приложения", "Backend for frontend")
}

Rel(appUsing, cntIdP, "Аутентифицируется и получает JWT-токен доступа.")


@enduml