@startuml

title Диаграмма системы Saas-PigSystem

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

System(users, "Роли", "Используют части системы в зависимости от должностных обязанностей и уровня допуска")
Container_Boundary(users, "Пользователи и роли"){

    Person(userDir, "Руководство", "Принимает решения по управлению хозяйством")
    Person(userAdmin, "Администратор PigSystem", "Управляет списком аккаунтов пользователей и их правами доступа. Следит за здоровьем системы")
}

System_Ext(sysIntegrating, "Интегрирующие системы", "Обрабатывают интересующие метрики")


Rel_Down(userDir, appUsing, "Просматривает статистику и аналитику по деятельности ферм")
Rel_Down(userAdmin, appAdministrating, "Администрирует систему PigSystem")

Rel_Right(PigFarmSystem, sysIntegrating, "Поставляет настраиваемые базовые и специфические метрики")

@enduml