@startuml
title Диаграмма системы АгроТех Х PigSystem

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

System(users, "Пользователи и роли", "Используют части системы в зависимости от занимаемой должности")

Container_Boundary(users, "Пользователи и роли"){

    'using items
    Person(userDir, "Директор хозяйства", "Может работать вне фермы. Пользуется статистикой и аналитикой для управления хозяйством")
    Person(userOnDuty, "Дежурный", "Работает на ферме, исполняет протоколы дежурства, реагирует на события")
    Person(userVet, "Ветеринар", "Работает на ферме, следит за здоровьем животных")
    Person(userMech, "Механик", "Работает на ферме, следит за состоянием оборудования")
}

'external items
System_Ext(appUsing, "Mобильное или Web приложение", "Предоставляет интерфейс для работы с PigSystem")
System_Ext(sysIntegrating, "Интегрирующая система", "Собирает интересующие метрики")

'system itself
System(PigFarmSystem, "Pig System", "Автоматизирует свиноводческое хозяйство")

Container_Boundary(PigFarmSystem, "Pig System"){
    Container(backCenter, "Центральный сервер", "", "Агрегирует данные всей системы и ее ферм. Предоставляет статистику и аналитику.")
    Container(backFarm1, "Сервер-агент1", "", "Автоматизирует конкретную ферму")
    Container(backFarmN, "Сервер-агентN", "", "Автоматизирует конкретную ферму")
}

Rel(backCenter, backFarm1, "Собирает информацию")
Rel(backCenter, backFarmN, "Собирает информацию")

'using relations
Rel_Down(userDir, appUsing, "Просматривает статистику и аналитику по деятельности фермы")
Rel_Down(userOnDuty, appUsing, "Просматривает информацию о состоянием фермы,\r\nуправляет устройствами кормления,\r\nполучает оповещения о событиях\r\nотчитывается о предпринятых действиях\r\n")
Rel_Down(userVet, appUsing, "Просматривает информацию о состоянии и здоровье животных,\r\nполучает оповещения о событиях,\r\nотчитывается о предпринятых действиях\r\n")
Rel_Down(userMech, appUsing, "Просматривает информацию о состоянии оборудования,\r\nполучает оповещения о событиях, отчитывает о предпринятых действиях\r\n")

Rel_Down(appUsing,backCenter,"Аутентификация, просмотр статистики и аналитики по хозяйству")
Rel(appUsing,backFarm1,"Управление фермой1")
Rel(appUsing,backFarmN,"Управление фермойN")

' in use relations

Rel_Right(backCenter, sysIntegrating, "Поставляет настраиваемые базовые и специфические метрики")

@enduml