@startuml
title Диаграмма контейнеров системы АгроТех Х PigSystem

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

System(PigFarmSystem, "Автоматизация свиноводческого хозяйства", " ")
System_Boundary(PigFarmSystem, ""){
    
    System(dSystem, "Домен: PigSystem как система", " ")
    System_Boundary(dSystem, ""){    

        System(dUsers, "Поддомен: Взаимодействие с пользователями", " ")
        System_Boundary(dUsers, ""){    
            System( sysAutentification, "Контекст: Многофакторная аутентификация", "Проводит пользователя по этапам многофакторной аутентификации")    
            System( sysUsersManagement, "Контекст: Управление доступами", "Управление аккаунтами пользователей, их ролями и политиками доступа")    
            System( sysAPIGateway, "Контекст: API для клиентских приложений", "Предоставление API для запросов, отправления команд и получения оповещений о событиях. Валидирует JWT-токены")    
            System( sysUsersActivity, "Контекст: Отслеживание активности пользователя", "Лог действий пользователя, важных для безопасности")    

        }

        System(dIntegrations, "Поддомен: Взаимодействие с внешними системами", " ")
        System_Boundary(dIntegrations, ""){    
            System( sysIntegration, "Контекст: Интеграция с внешними системами","Передает стандартные и специфические метрики в интегрирующие системы\r\nУправляет списком метрик")    
        }

        System(dPing, "Поддомен: Поддержание целостности системы", " ")
        System_Boundary(dPing, ""){    
            System( sysStore, "Контекст: Хранение данных", "Сохранение истории системы")    
            System( sysPing, "Контекст: Мониторинг связи","Между сервером-центром, серверами-агентами, внешними системами")    
        }
    }


    System(dPigs, "Домен: Уход за животными", " ")
    System_Boundary(dPigs, ""){ 

        System(dPigState, "Поддомен: Присмотр за животными", " ")
        System_Boundary(dPigState, ""){ 
            System( sysPigsBehaviour, "Контекст: Мониторинг поведения животных", "Признаки беспокойства, гибель, задавливания поросят итд")    
            System( sysPigsState, "Контекст: Мониторинг состояния животных", "Пересчет особей, здоровыъ и с признаками болезни и т д")
        }

        System(dPigFeeding, "Поддомен: Кормление животных", " ")
        System_Boundary(dPigFeeding, ""){ 
            System( sysFeedingEquipment, "Контекст: Автоматизация кормления", "Работа с поилками и кормушками. График кормления.")    
            
            System(dPigFeedingSupply, "Снабжение кормом", " ")
            System_Boundary(dPigFeedingSupply, ""){ 
                System( sysFeedingResources, "Контекст: Мониторинг запасов", "Отслеживание запасов корма итд")    
                System( sysFeedingForecast, "Контекст: Прогнозирование запасов", "Рассчет необходимого количества корма в зависимости от графика кормления и поголовья стада")    
            
            }        
        }
    }

    System(dEquipment, "Домен: Использование оборудования автоматизации", "Edge-устройства разных производителей: поилки, кормушки, видеокамеры")
    System_Boundary(dEquipment, ""){    
        
        System(dEquipmentKnowledge, "Поддомен: Учет полевого оборудования", "")
        System_Boundary(dEquipmentKnowledge, ""){                
            System( sysEquipmentList, "Контекст: Ведение полевой карты", "Поддерживать список полевого оборудования системы, его расположение на территории, его тип интеграции")    
            System( sysEquipmentState, "Контекст: Мониторинг состояния полевого оборудования", "Отслеживать техническое состояние и сигнал связи")    
        }

        System(dEquipmentIntegration, "Поддомен: Взаимодействие с полевым оборудованием", "")
        System_Boundary(dEquipmentIntegration, ""){                
            
            System( sysEdgeData, "Контекст: Схемы интеграции", "Приведение сообщений и команд устройства к стандартизованному списку, который понимает PigSystem")    
            
            System( sysEdgeII, "Контекст: Распознавание поведения животных", "Интеграция ИИ-модели распознавания для мониторинга поведения и состояния животных от партнеров")    

            System( sysEdgeGateway, "Контекст: Интеграционный мост", "Сообщает канал общения полевого оборудования и канал общения PigSystem")    
        }    
    
    }
}



@enduml