@startuml
title Диаграмма контейнеров системы АгроТех Х PigSystem

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

System(PigFarmSystem, "Автоматизация свиноводческого хозяйства", " ")
System_Boundary(PigFarmSystem, ""){
    
    System(dSystem, "Домен: PigSystem как система", " ")
    System_Boundary(dSystem, ""){    

        System(dUsers, "Поддомен: Взаимодействие с пользователями", " ")
        System_Boundary(dUsers, ""){    
            System( sysAutentification, "Многофакторная аутентификация", "Проводит пользователя по этапам многофакторной аутентификации")    
            System( sysUsersManagement, "Управление доступами", "Управление аккаунтами пользователей, их ролями и политиками доступа")    
            System( sysAPIGateway, "API для клиентских приложений", "Предоставление API для запросов, отправления команд и получения оповещений о событиях. Валидирует JWT-токены")    
            System( sysUsersActivity, "Отслеживание активности пользователя", "Лог действий пользователя, важных для безопасности")    

        }

        System(dIntegrations, "Поддомен: Взаимодействие с внешними системами", " ")
        System_Boundary(dIntegrations, ""){    
            System( sysIntegration, "Интеграция с внешними системами","Передает стандартные и специфические метрики в интегрирующие системы\r\nУправляет списком метрик")    
        }

        System(dPing, "Поддомен: Поддержание целостности системы", " ")
        System_Boundary(dPing, ""){    
            System( sysStore, "Хранение данных", "Сохранение истории системы")    
            System( sysPing, "Мониторинг связи","Между сервером-центром, серверами-агентами, внешними системами")    
        }
    }


    System(dPigs, "Домен: Уход за животными", " ")
    System_Boundary(dPigs, ""){ 

        System(dPigState, "Поддомен: Присмотр за животными", " ")
        System_Boundary(dPigState, ""){ 
            System( sysPigsBehaviour, "Мониторинг поведения животных", "Признаки беспокойства, гибель, задавливания поросят итд")    
            System( sysPigsState, "Мониторинг состояния животных", "Пересчет особей, признаки болезни")
        }

        System(dPigFeeding, "Поддомен: Кормление животных", " ")
        System_Boundary(dPigFeeding, ""){ 
            System( sysFeedingEquipment, "Автоматизация кормления", "Работа с поилками и кормушками. График кормления.")    
            
            System(dPigFeedingSupply, "Снабжение кормом", " ")
            System_Boundary(dPigFeedingSupply, ""){ 
                System( sysFeedingResources, "Мониторинг запасов", "Отслеживание запасов корма итд")    
                System( sysFeedingForecast, "Прогнозирование запасов", "Рассчет необходимого количества корма в зависимости от графика кормления и поголовья стада")    
            
            }        
        }
    }

    System(dEquipment, "Домен: Использование оборудования автоматизации", "Edge-устройства разных производителей: поилки, кормушки, видеокамеры")
    System_Boundary(dEquipment, ""){    
        
        System( sysEquipmentState, "Мониторинг полевого оборудования", "Учет устройств, их расположение, техническое состояние и сигнал связи")    
    
        System(dEquipmentIntegration, "Взаимодействие с полевым оборудованием", "")
        System_Boundary(dEquipmentIntegration, ""){                
            
            System( sysEdgeData, "Схемы интеграции", "Приведение сообщений и команд устройства к стандартизованному списку, который понимает PigSystem")    
            
            System( sysEdgeII, "Распознавание поведения животных", "Интеграция ИИ-модели распознавания для мониторинга поведения и состояния животных от партнеров")    

            System( sysEdgeGateway, "Интеграционный мост", "Сообщает канал общения полевого оборудования и канал общения PigSystem")    
        }    
    
    }

    '    Container(backCenter, "Центральный сервер", "", "Агрегирует данные всей системы и ее ферм. Предоставляет статистику и аналитику.")
}



@enduml