@startuml
title Диаграмма микросервисов и их взаимодействия в системе АгроТех Х PigSystem

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(userAll, "Все", "Дежурный, Ветеринар, Инженер/механик, Снабжение")

Person(userSupply, "Снабжение", "Обеспечивает запас корма")
Person(userOnDuty, "Дежурный", "Исполняет протоколы дежурства на конкретной ферме")
Person(userVet, "Ветеринар", "Следит за здоровьем животных на фермах")
Person(userMech, "Инженер/Механик", "Следит за состоянием оборудования на фермах")

    'Поддержание целостности
    System(backIntegrity, "Поддержание целостности","")
    Container_Boundary(backIntegrity, "") {
    
        System(backIntegrityCenter, "Центр","")
        Container_Boundary(backIntegrityCenter, "") {
            Container(cntIntegrityStore, "Сервис сохранения событий системы", "", "Сохраняет историю событий всей системы")
            Container(cntIntegrityIntegration, "Сервис интеграции", "", "Передает метрики в интегрирующие системы. Управляет списком метрик") 
            Container(cntIntegrityPing, "Сервис мониторинга связи с серверами-агентами", "", "Передает метрики в интегрирующие системы. Управляет списком метрик") 
        }

        Container(cntIntegrityBroker, "Шина сообщений", "", "") {
            Component_Ext(cmpIntegrityCenter, "Все сообщения центра")
            Component(cmpIntegrityFarm, "Все сообщения с фермы")
            Component_Ext(cmpIntegrityIntegration, "Метрики для интеграция")
            Component(cmpIntegrityPing, "Агент на связи")
            Component(cmpIntegrityNotification, "Оповещение пользователям")
        }

        System(backIntegrityFarm, "Ферма","")
        Container_Boundary(backIntegrityFarm, "") {
            Container(cntIntegritySync, "Сервис синхронизации сервера-агента", "", "Транслирует сообщения между центральной щиной и локальной шиной сообщений") 
        }

        Container_Ext(extIntegrityNotification, "Сервис оповещения пользователей", "", "Взаимодействие с пользователями")
    }

    Rel_Up(cmpIntegrityCenter,cntIntegrityStore,"Подписан")
    Rel_Up(cmpIntegrityFarm,cntIntegrityStore,"Подписан")
    
    Rel_Up(cntIntegritySync,cmpIntegrityPing,"Публикует")
    Rel_Up(cmpIntegrityPing,cntIntegrityPing,"Подписан")

    Rel_Up(cmpIntegrityIntegration,cntIntegrityIntegration,"Подписан")

    Rel_Up(cntIntegritySync,cmpIntegrityFarm,"Публикует")
    Rel(cmpIntegrityCenter,cntIntegritySync,"Подписан")

    Rel_Up(cntIntegritySync,cmpIntegrityNotification,"Публикует события изменения связи")
    Rel_Down(cmpIntegrityNotification,extIntegrityNotification,"Подписан")

'    Rel(,,"Подписан")
    'Взаимодействие с пользователями
    System(backManagement, "Взаимодействие с пользователями","")
    Container_Boundary(backManagement, "") {
        
        System(backManagementCenter, "Центр","")
        Container_Boundary(backManagementCenter, "") {
            Container(cntAgentManagementUsers, "Сервис управления аккаунтами пользователей", "", "Настройки и доступы")
        }
        
        System(backManagementFarm, "Ферма","")
        Container_Boundary(backManagementFarm, "") {
            Container(cntAgentMonitorUsers, "Сервис мониторинга аккаунтов пользователя", "", "Предоставляет актуальный список пользователей и их настроек на ферме") 
        }
        
        Container(cntAgentNotification, "Сервис оповещения", "", "Оповещает пользователей о важных событиях") 

        Container(cntAgentManagementBroker, "Шина сообщений", "", "") {
            Component_Ext(cmpAgentNotification, "Оповещения\nпользователям")
            Component(cmpAgentManagementUsers, "Изменения в аккаунтах пользователей")
        }

        Container_Ext(extAgentNotificationFeeding,"Сервис автоматизации кормления", "")
        Container_Ext(extAgentNotificationEquipMonitoring, "Сервис мониторинга оборудовния","", "Учет полевого оборудования")
        Container_Ext(extAgentNotificationPigsBehaviour,"Сервис мониторинга поведения животных", "", "Присмотр за животными")
        Container_Ext(extAgentNotificationPigsState,"Сервис мониторинга состояния животных", "", "Присмотр за животными")
        Container_Ext(extAgentNotificationPing,"Сервис синхронизации сервера-агента", "", "Поддержание целостности")
    }

    Rel(cntAgentManagementUsers,cmpAgentManagementUsers, "Публикует")
    Rel_Up(cmpAgentManagementUsers,cntAgentNotification, "Подписан")
    Rel_Up(cmpAgentManagementUsers,cntAgentMonitorUsers, "Подписан")

    Rel_Up(extAgentNotificationFeeding,cmpAgentNotification, "Публикует значимые события автоматизации кормления")
    Rel_Up(extAgentNotificationEquipMonitoring,cmpAgentNotification, "Публикует значимые события мониторинга оборудования")
    Rel_Up(extAgentNotificationPigsState,cmpAgentNotification, "Публикует значимые события о состоянии животных")
    Rel_Up(extAgentNotificationPigsBehaviour,cmpAgentNotification, "Публикует значимые события о поведении животных")
    Rel_Up(extAgentNotificationPing,cmpAgentNotification, "Публикует значимые события о состоянии связи с центром")
    Rel_Up(cmpAgentNotification,cntAgentNotification, "Подписан")
    Rel_Up(cntAgentNotification,userAll,"Оповещает")

    'Присмотр за животными
    System(backPigsState, "Присмотр за животными","")
    Container_Boundary(backPigsState, "") {

        Container(cntAgentPigsBehaviour, "Сервис мониторинга поведения животных", "", "Признаки беспокойства, гибель, задавливание поросят и т д")
        Container(cntAgentPigsState, "Сервис мониторинга состояния животных", "", "Пересчет особей, здоровых и с признаками болезни и т д")
        
        Container(cntAgentBrokerPigsState, "Шина сообщений", "", "") {
            Component(cmpPigsStateNotification, "Оповещения\nпользователям")
            Component(cmpPigsStateCount, "Текущее поголовье")
            Component_Ext(cmpPigsStateData, "Стандартизованные события\nо состоянии животных\nот оборудования")
            Component_Ext(cmpPigsBehaviourData, "Стандартизованные события\nо поведении животных\nот оборудования")
            Component_Ext(cmpPigsStateFeedingEquipPlace, "События\nоб изменении списка устройств и их расположения")
        }
        
        Container_Ext(extPigsStateNotification,"Сервис оповещения", "", "Взаимодействие с пользователями")
        Container_Ext(extPigsStateAdapters, "Сервисы-адаптеры устройств","","Взаимодействие с оборудованием")
        Container_Ext(extPigsStateForecast, "Сервис прогнозирования запасов корма","","Снабжение кормом")
        Container_Ext(extPigsStateEquipPlace,"Сервис ведения полевой карты", "","Учет оборудования")
    }
    Rel_Up(extPigsStateEquipPlace,cmpPigsStateFeedingEquipPlace,"Публикует")
    Rel_Up(cmpPigsStateFeedingEquipPlace,cntAgentPigsBehaviour,"Подписан")
    Rel_Up(cmpPigsStateFeedingEquipPlace,cntAgentPigsState,"Подписан")

    Rel(cntAgentPigsState,cmpPigsStateCount,"Публикует")
    Rel(cmpPigsStateCount,extPigsStateForecast,"Подписан")

    Rel(cntAgentPigsBehaviour,cmpPigsStateNotification, "Публикует значимые события о поведении животных")
    Rel(cntAgentPigsState,cmpPigsStateNotification, "Публикует значимые события о состоянии животных")
    Rel(cmpPigsStateNotification,extPigsStateNotification, "Подписан")
    
    Rel_Up(extPigsStateAdapters,cmpPigsStateData, "Публикует")
    Rel_Up(extPigsStateAdapters,cmpPigsBehaviourData, "Публикует")
    Rel(cmpPigsBehaviourData,cntAgentPigsBehaviour, "Подписан")
    Rel(cmpPigsStateData,cntAgentPigsState, "Подписан")

    Rel(userOnDuty,cntAgentPigsBehaviour,"Использует")
    Rel(userOnDuty,cntAgentPigsState,"Использует")
    Rel(userVet,cntAgentPigsState,"Использует")

    'Снабжение кормом
    System(backSupply, "Снабжение кормом","")
    Container_Boundary(backSupply, "") {
        
        Container(cntAgentSupplyState, "Сервис мониторинга запасов корма", "", "Отслеживание запасов корма")        
        Container(cntAgentSupplyForecast, "Сервис прогнозирования запасов корма", "", "Расчет необходимого количества корма в зависимости от графика кормления и поголовья скота")        

        Container(cntAgentBrokerSupply, "Шина сообщений", "", "") {
            Component(cmpAgentSupplyForecastResponse, "Прогноз расходов запасов")
            Component(cmpAgentSupplyNotification, "Оповещения\nпользователям")
            Component_Ext(cmpAgentSupplyFeedingSpent, "Скормлено за день")
            Component_Ext(cmpAgentSupplyFeedingSize, "Нормы кормления")
            Component_Ext(cmpAgentSupplyPigsCount, "Текущее поголовье")
        }

        Container_Ext(extSupplyNotification, "Сервис оповещения","", "Взаимодействие с пользователями")
        Container_Ext(extSupplyFeeding,"Сервис автоматизации кормления", "")
        Container_Ext(extSupplyPigsState, "Сервис мониторинга состояния животных","","Присмотр за животными")
    }
    Rel(cntAgentSupplyForecast,cmpAgentSupplyForecastResponse,"Публикует")
    Rel_Up(cmpAgentSupplyForecastResponse,cntAgentSupplyState,"Подписан")
    
    Rel_Up(extSupplyPigsState,cmpAgentSupplyPigsCount,"Публикует")
    Rel(cmpAgentSupplyPigsCount,cntAgentSupplyForecast,"Подписан")

    Rel_Down(cntAgentSupplyState, cmpAgentSupplyNotification, "Публикует значимые события уровня запасов корма")
    Rel_Down(cmpAgentSupplyNotification,extSupplyNotification,"Подписан")
    
    Rel_Up(cmpAgentSupplyFeedingSpent,cntAgentSupplyState,"Подписан")
    Rel_Up(extSupplyFeeding,cmpAgentSupplyFeedingSpent, "Публикует")

    Rel_Up(cmpAgentSupplyFeedingSize,cntAgentSupplyForecast,"Подписан")
    Rel_Up(extSupplyFeeding,cmpAgentSupplyFeedingSize,"Публикует")

    Rel(userSupply,cntAgentSupplyState,"Использует")

    'Кормление животных
    System(backPigs, "Кормление животных","")
    Container_Boundary(backPigs, "") {

        Container(cntAgentPigsFeeding, "Сервис автоматизации кормления", "", "Работа с поилками и кормушками. График кормления")

        Container(cntAgentBrokerPigs, "Шина сообщений", "", "") {
            Component(cmpPigsFeedingNotification, "Оповещения\nпользователям")
            Component(cmpPigsFeedingCmd, "Стандартизованные команды оборудования")
            Component(cmpPigsFeedingSettings, "Нормы кормления")
            Component(cmpPigsFeedingSpent, "Скормлено за день")
            Component_Ext(cmpPigsFeedingData, "Стандартизованные события\nавтоматизации кормления\nот оборудования")
            Component_Ext(cmpPigsFeedingEquipPlace, "События\nоб изменении списка устройств и их расположения")
        }
        Container_Ext(extPigsEquipPlace,"Сервис ведения полевой карты", "","Учет оборудования")
        Container_Ext(extPigsNotification,"Сервис оповещения", "", "Взаимодействие с пользователями")
        Container_Ext(extPigsAdapters,"Сервисы-адаптеры устройств", "","Взаимодейтсвие с оборудованием")
        Container_Ext(extPigsForecast,"Сервис прогнозирования запасов корма", "", "Снабжение кормом")
        Container_Ext(extPigsMonitor,"Сервис мониторинга запасов корма", "", "Снабжение кормом")
    }

    Rel_Up(extPigsEquipPlace,cmpPigsFeedingEquipPlace,"Публикует")
    Rel_Up(cmpPigsFeedingEquipPlace,cntAgentPigsFeeding,"Подписан")

    Rel_Down(cntAgentPigsFeeding,cmpPigsFeedingNotification, "Публикует значимые события в автоматизированном кормлении")
    Rel_Down(cmpPigsFeedingNotification,extPigsNotification, "Подписан")
    
    Rel(cntAgentPigsFeeding,cmpPigsFeedingSettings, "Публикует")
    Rel_Down(cmpPigsFeedingSettings,extPigsForecast, "Подписан")
    
    Rel(cntAgentPigsFeeding,cmpPigsFeedingSpent, "Публикует")
    Rel_Down(cmpPigsFeedingSpent,extPigsMonitor, "Подписан")
    
    Rel(cntAgentPigsFeeding,cmpPigsFeedingCmd, "Публикует")
    Rel_Down(cmpPigsFeedingCmd,extPigsAdapters, "Подписан")
    
    Rel_Up(extPigsAdapters,cmpPigsFeedingData, "Публикует")
    Rel(cmpPigsFeedingData,cntAgentPigsFeeding, "Подписан")

    Rel(userOnDuty,cntAgentPigsFeeding,"Использует")

    'Учет полевого оборудования
    System(backEquipment, "Учет полевого оборудования","")
    Container_Boundary(backEquipment, "") {
    
        Container(cntEquipMonitoring, "Сервис мониторинга оборудования", "", "Отслеживает техническое состояние и сигнал связи") 
        Container(cntEquipMap, "Сервис ведения полевой карты", "", "Ведет список полевого оборудования , его расположение на территории, его тип интеграции") 

        Container(cntAgentBrokerEquipment, "Шина сообщений", "", "") {

            Component(cmpEquipMonitoringNotification, "Оповещения\nпользователям")
            Component(cmpEquipType, "События\nоб изменении списка устройств и их типов")
            Component(cmpEquipPlace, "События\nоб изменении списка устройств и их расположения")
            Component_Ext(cmpEquipStandartData2, "Стандартизованные технические события от оборудования")
        }
        Container_Ext(extEquipMonitoringNotification, "Сервис оповещения", "", "Взаимодействие с пользователями")
        Container_Ext(extEquipmentAdapters, "Сервисы-адаптеры устройств", "","Взаимодействие с оборудованием")

        Container_Ext(extEquipmentPigState,"Сервис мониторинга состояния животных", "", "Присмотр за животными")
        Container_Ext(extEquipmentPigBehaviour,"Сервис мониторинга поведения животных", "", "Присмотр за животными")
        Container_Ext(extEquipmentFeeding,"Сервис автоматизации кормления", "")
    }

    Rel_Down(cntEquipMap,cmpEquipType, "Публикует")
    Rel(cntEquipMap,cmpEquipPlace, "Публикует")

    Rel_Up(cmpEquipPlace,cntEquipMonitoring, "Подписан")
    Rel_Down(cntEquipMonitoring,cmpEquipMonitoringNotification, "Публикует значимые события на оборудовании")

    Rel_Down(cmpEquipMonitoringNotification,extEquipMonitoringNotification, "Подписан")
    Rel_Down(cmpEquipType,extEquipmentAdapters, "Подписан")

    Rel_Up(cmpEquipStandartData2,cntEquipMonitoring, "Подписан")
    Rel_Up(extEquipmentAdapters,cmpEquipStandartData2,"Публикует")

    Rel(userMech,cntEquipMonitoring,"Использует")
    Rel(userMech,cntEquipMap,"Использует")

    Rel_Down(cmpEquipPlace,extEquipmentPigState,"Подписан")
    Rel_Down(cmpEquipPlace,extEquipmentPigBehaviour,"Подписан")
    Rel_Down(cmpEquipPlace,extEquipmentFeeding,"Подписан")

    'Взаимодействие с полевым оборудованием
    System(backEquipmentUsing, "Взаимодействие с полевым оборудованием","")
    Container_Boundary(backEquipmentUsing, "") {

        Container_Ext(extEquipmentUsingEquipMap,"Сервис ведения полевой карты", "","Учет оборудования")
        Container_Ext(extEquipmentUsingFeeding,"Сервис автоматизации кормления", "")
        Container_Ext(extEquipmentUsingEquipMonitor,"Сервис мониторинга оборудования", "","Учет оборудования")
        Container_Ext(extEquipmentUsingPigState,"Сервис мониторинга состояния животных", "", "Присмотр за животными")
        Container_Ext(extEquipmentUsingPigSBehaviour, "Сервис мониторинга поведения животных","", "Присмотр за животными")

        Container(cntAgentBrokerEquipmentUsing, "Шина сообщений", "", "") {

            Component(cmpEquipSpecificData, "События\ncпецифические для оборудования")
            Component(cmpEquipSpecificCmd, "Команды\nспецифические для оборудования")

            Component(cmpEquipStandardDataEquipment, "Стандартизованные технические события\nот оборудования")
            Component(cmpEquipStandardDataFeeding, "Стандартизованные события\nавтоматизации кормления\nот оборудования")
            Component(cmpEquipStandardDataPigsState, "Стандартизованные события\nо состоянии животных\nот оборудования")
            Component(cmpEquipStandardDataPigsBehaviour, "Стандартизованные события\nо поведении животных\nот оборудования")

            Component_Ext(cmpEquipStandardCmd, "Стандартизованные команды\nоборудованию")
            Component_Ext(cmpEquipType2, "События\nоб изменении списка устройств и их типов")
        }
        Container(cntAgentEquipmentAdapter, "Сервисы-адаптеры устройств", "", "Перводчик со стандартных для PigSystem сообщений и команд к специфическим для производителя устройства и обратно")
        Container(cntAgentEquipmentVideo, "Сервис сбора видеофрагментов", "", "Сохраняет видеофрагменты зарегистрированных событий в локальное хранилище")

        Container(cntAgentEdgeGateway, "IOT Шлюз", "", "Транслирует обмен сообщений с Edge-устройствами в локальный брокер сообщений") 
        Container(cntAgentIIServer, "Серверный ИИ-агент", "", "Анализирует видеопоток и инициироует сообщения о зарегистрированных событиях") 
    } 
    
    Rel_Down(cntAgentEquipmentAdapter,cmpEquipStandardDataEquipment, "Публикует")
    Rel_Down(cntAgentEquipmentAdapter,cmpEquipStandardDataFeeding, "Публикует")
    Rel_Down(cntAgentEquipmentAdapter,cmpEquipStandardDataPigsState, "Публикует")
    Rel_Down(cntAgentEquipmentAdapter,cmpEquipStandardDataPigsBehaviour, "Публикует")
    
    Rel_Up(cmpEquipStandardDataPigsState,cntAgentEquipmentVideo, "Подписан")
    Rel_Up(cmpEquipStandardDataPigsBehaviour,cntAgentEquipmentVideo, "Подписан")
    
    
    Rel_Down(cmpEquipStandardDataEquipment,extEquipmentUsingEquipMonitor, "Подписан")
    Rel(cmpEquipStandardDataFeeding,extEquipmentUsingFeeding, "Подписан")
    Rel(cmpEquipStandardDataPigsState,extEquipmentUsingPigState, "Подписан")
    Rel(cmpEquipStandardDataPigsBehaviour,extEquipmentUsingPigSBehaviour, "Подписан")

    Rel_Up(extEquipmentUsingFeeding,cmpEquipStandardCmd, "Публикует")
    Rel(cmpEquipStandardCmd,cntAgentEquipmentAdapter, "Подписан")

    Rel(cmpEquipSpecificData,cntAgentEquipmentAdapter, "Подписан")
    Rel(cntAgentEquipmentAdapter,cmpEquipSpecificCmd, "Публикует")

    Rel_Up(extEquipmentUsingEquipMap,cmpEquipType2, "Публикует")    
    Rel_Up(cmpEquipType2,cntAgentEquipmentAdapter, "Подписан")

    Rel_Down(cntAgentIIServer,cmpEquipSpecificData, "Публикует")
    Rel_Down(cntAgentEdgeGateway,cmpEquipSpecificData, "Публикует")
    Rel(cmpEquipSpecificCmd,cntAgentEdgeGateway, "Подписан")

Lay_Right(cntAgentBrokerPigs,cntAgentBrokerPigsState)     
Lay_Right(cntAgentBrokerPigsState,cntAgentBrokerSupply)
Lay_Right(cntAgentBrokerSupply,cntAgentBrokerEquipment)
Lay_Right(cntAgentBrokerEquipment,cntAgentBrokerEquipmentUsing)
Lay_Right(cntAgentBrokerEquipmentUsing,cntIntegrityBroker)
Lay_Right(cntIntegrityBroker,cntAgentManagementBroker)

Lay_Right(backPigs,backPigsState)     
Lay_Right(backPigsState,backSupply)
Lay_Right(backSupply,backEquipment)
Lay_Right(backEquipment,backEquipmentUsing)
Lay_Right(backEquipmentUsing,backIntegrity)
Lay_Right(backIntegrity,backManagement)

'backPigs backPigsState backSupply backEquipment backEquipmentUsing backIntegrity backManagement
'cntAgentBrokerPigs cntAgentBrokerPigsState cntAgentBrokerSupply cntAgentBrokerEquipment cntAgentBrokerEquipmentUsing cntIntegrityBroker cntAgentManagementBroker 
@enduml