@startuml
title Диаграмма контейнеров инфраструктуры мультитенантной системы АгроТех Х PigSystem

'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!include ../C4_Component.puml

'external items
System_Ext(appAgentUsing, "Пользовательский интерфейс оперативного управления фермой", "Mобильное или Web приложение для использования PigSystem")
System_Ext(sysIntegrating, "Цифровая платформа AgroTech", "Обрабатывает интересующие метрики")

Person(userDir, "Руководство", "Принимает решения по управлению хозяйством")

Person(userSupply, "Снабжение", "Обеспечивает запас корма")
Person(userOnDuty, "Дежурный", "Исполняет протоколы дежурства на конкретной ферме")
Person(userVet, "Ветеринар", "Следит за здоровьем животных на фермах")
Person(userMech, "Инженер/Механик", "Следит за состоянием оборудования на фермах")

Rel(userDir, sysIntegrating, "Использует")

Rel(userSupply, appAgentUsing, "Использует")
Rel(userOnDuty, appAgentUsing, "Использует")
Rel(userVet, appAgentUsing, "Использует")
Rel(userMech, appAgentUsing, "Использует")

'center
System(backCenter, "Центральный сервер"," ")
Container_Boundary(backCenter, "") {

    System(sysCenterUsers, "Центр: Взаимодействие с пользователями")
    Container_Boundary(sysCenterUsers, ""){
        Container(cntIdP, "Identity Provider", "Keycloak", "Управляет аккаунтами пользователей и их правами доступа\n\nПроводит через аутентификацию")
        Container(cntCenterUsers, "Сервис управления аккаунтами пользователей", "", "Хранит информацию о настройках аккаунтов\n\nМультитенантен, использует контекст тенанта")

        Container(cntCenterAPIGateway, "API Gateway", "Kong Gateway", "Валидирует токены доступа\nМаршрутизирует запросы")

        Container(cntCenterNotification, "Сервис оповещения пользователей", "", "Управляет оповещениями пользователей\n\nМультитенантен, использует контекст тенанта")

        Container(cntCenterTenants, "Сервис тенантов", "", "Управляет\nучетными данными\nтенантов")
    }
    
    System(sysCenterIntegrity, "Центр: Поддержание целостности")
    Container_Boundary(sysCenterIntegrity, ""){
        Container(cntCenterStore, "Сервис сохранения истории", "", "Сохранение истории событий всей системы\n\nМультитенантен, использует контекст тенанта")
        Container(cntCenterIntegrating, "Сервис интеграции", "", "Транслирует настраиваемые метрики во внешнюю систему\n\nМультитенантен, использует контекст тенанта")
        ContainerDb(cntCenterDb, "Центральное хранилище", "S3", "Хранит данные всей системы. Данные помечены tenantID")

        Container(cntCenterSync, "Сервис приема синхронизации агентов", "", "Принимает сообщения с агентов ферм\n публикует их в центральную шину сообщений с пометкой TenantId и транслирует фермам сообщения центра соответствующих TenantId\n\nМультитенантен") 
    }

    System(sysAgentManagement, "Центр: Операционное управление фермой","Учет полевого оборудования\nКормление животных\nСнабжение кормом\nПрисмотр за животными")
    Container_Boundary(sysAgentManagement, "") {
        Container(cntCenterManagement, "Сервисы операционного управления фермой", "", "Мультитенантны, используют контекст тенанта") 
    }


    Container(cntCenterBroker, "Центральный брокер сообщений", "Kafka", "Среда обмена сообщениями Центра и ферм\n                                                                                                                                                                                                     ") 
 }  
'farm agent
System(backFarm1, "Сервер-агент на ферме","")
Container_Boundary(backFarm1, "") {

    System(sysAgentIntegrity, "","Сервер-Агент: Поддержание целостности")
    Container_Boundary(sysAgentIntegrity, "") {

        Container(cntAgentSync, "Сервис синхронизации с центром", "", "Гарантирует передачу сообщений в центр даже при разрывах связи")
    } 
 }

'Laying
'    Lay_Right(sysIntegrating, appAgentUsing)
    Lay_Right(userDir, userOnDuty)
    
    'center blocks
    Lay_Right(sysCenterIntegrity, sysCenterUsers)
    Lay_Down(sysCenterUsers, cntCenterBroker)

    'geo areas
    Lay_Down(backCenter, backFarm1)

    Lay_Right(cntCenterTenants, cntCenterNotification)
    Lay_Right(cntIdP, cntCenterUsers)
    Lay_Right(cntCenterUsers, cntCenterTenants)
'Relations
    ' external
    Rel(appAgentUsing, cntCenterAPIGateway, "Использует функции системы в зависимости от прав доступа пользователей")
    Rel(appAgentUsing, cntIdP, "Аутентифицируется и получает JWT-токен доступа.")
    Rel_Up(cntCenterIntegrating, sysIntegrating, "Публикует настраиваемый список метрик")
    Rel_Up(cntCenterNotification, appAgentUsing, "Оповещения")

    'center broker
    Rel_Left(cntCenterUsers, cntIdP, "Синхронизованный список аккаунтов, их настроек и доступов")
    Rel(cntCenterUsers, cntCenterBroker, "Публикует изменения\nв настройках пользователей\nОбогащены TenantId")
    Rel_Down(cntCenterBroker, cntCenterStore, "Все\nсообщения\nОбогащены TenantId")
    Rel_Down(cntCenterBroker, cntCenterIntegrating, "Настраиваемый\nсписок\nсообщений")
    Rel(cntCenterStore, cntCenterDb, "Все\nсообщения\nОбогащены TenantId")
    Rel_Down(cntCenterSync, cntCenterDb, "Все\nвидеофрагменты\nОбогащены TenantId")
    BiRel_Up(cntCenterSync, cntCenterBroker, "Транслирует\nсообщения\nОбогащены TenantId")

    Rel(cntCenterAPIGateway, cntCenterManagement, "Перенаправляет\nзапросы\nПредоставляет TenantID")
    
    BiRel_Up(cntCenterBroker, cntCenterManagement, "Команды\nСообщения\nОбогащены TenantId")

    'center-local
    Rel_Up(cntAgentSync, cntCenterSync, "Пакетно транслирует сообщения\nСигналит о наличии связи\nПередает идентификатор фермы\ngRPC Stream")

    'local broker
    'local broker integrity
    BiRel_Up(cntAgentBroker, cntAgentSync, "Сообщения для синхронизации с центром\nОбогащены TenantId")



    'center broker users
    Rel_Up(cntCenterBroker, cntCenterNotification, "Сообщения\nОбогащены TenantId")
    Rel(cntCenterAPIGateway, cntIdP, "Использует для валидации доступа и извлечения TenantID")
    Rel(cntCenterTenants, cntCenterBroker, "Взаимодействует")

@enduml
